spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/musicranker?serverTimezone=Asia/Seoul
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


